Repository activeloopai/deeplake, pull requests merged in 2021-05, with the labels that each got.

#799 Feature: multiple image loader function for extended folder structure in image classification
  hub/auto/computer_vision/classification.py
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class1/random_file.py
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class1/sample1.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class1/sample2.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class1/sample3.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class2/sample1.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class2/sample2.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class2/sample3.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class3/different_shape.jpeg
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class3/sample1.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class3/sample2.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/train/class3/sample3.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class1/random_file.py
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class1/sample1.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class1/sample2.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class1/sample3.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class2/sample1.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class2/sample2.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class2/sample3.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class3/different_shape.jpeg
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class3/sample1.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class3/sample2.png
  hub/auto/tests/dummy_data/image_classification/class_sample_multiple_folder/val/class3/sample3.png
  hub/auto/tests/test_image_classification.py
Labels: enhancement

#822 hub-2.0 chunk generator
  .circleci/config.yml
  .gitignore
  CONTRIBUTING.md
  hub/core/chunk_engine/__init__.py
  hub/core/chunk_engine/exceptions.py
  hub/core/chunk_engine/generator.py
  hub/core/chunk_engine/tests/test_generate_chunks.py
  hub/core/tests/test_placeholder.py
  requirements/common.txt
  requirements/tests.txt
  setup.cfg
Labels: enhancement, v2

#825 [Hub 2.0] API Skeleton
  hub/api/dataset.py
  hub/api/tensor.py
  hub/util/exceptions.py
  hub/util/slice.py
  hub/util/tests/__init__.py
  hub/util/tests/test_slice.py
  requirements/tests.txt
Labels: v2

#842 [2.0] writing/reading fixed-shape arrays to chunks
  .circleci/config.yml
  hub/constants.py
  hub/core/chunk_engine/__init__.py
  hub/core/chunk_engine/chunker.py
  hub/core/chunk_engine/generator.py
  hub/core/chunk_engine/read.py
  hub/core/chunk_engine/tests/common.py
  hub/core/chunk_engine/tests/test_chunker.py
  hub/core/chunk_engine/tests/test_fixed_shapes.py
  hub/core/chunk_engine/tests/test_utils.py
  hub/core/chunk_engine/util.py
  hub/core/chunk_engine/write.py
  hub/core/storage/__init__.py
  hub/core/storage/mapped_provider.py
  hub/core/storage/s3/s3_mapper.py
  hub/core/typing.py
  setup.cfg
Labels: enhancement

#851 [Hub 2.0] Adds support for caching
  hub/core/chunk_engine/read.py
  hub/core/chunk_engine/tests/common.py
  hub/core/chunk_engine/tests/test_fixed_shapes.py
  hub/core/chunk_engine/write.py
  hub/core/storage/__init__.py
  hub/core/storage/local.py
  hub/core/storage/lru_cache.py
  hub/core/storage/mapped_provider.py
  hub/core/storage/memory.py
  hub/core/storage/provider.py
  hub/core/storage/readme.md
  hub/core/storage/s3.py
  hub/core/storage/s3/s3.py
  hub/core/tests/test_storage_provider.py
  hub/core/typing.py
  hub/util/cache_chain.py
  hub/util/exceptions.py
  hub/util/tests/test_slice.py
  requirements/common.txt
Labels: v2

#861 Feature/2.0/pytest options
  .circleci/config.yml
  conftest.py
  hub/constants.py
  hub/core/__init__.py
  hub/core/chunk_engine/tests/common.py
  hub/core/chunk_engine/tests/test_benchmarks.py
  hub/core/chunk_engine/tests/test_fixed_shapes.py
  hub/core/storage/local.py
  hub/core/storage/s3.py
  hub/core/tests/common.py
  hub/core/tests/test_storage_provider.py
  hub/tests/__init__.py
  hub/tests/common.py
  hub/util/cache_chain.py
  setup.cfg
Labels: v2

#873 Fix/2.0/chunk sizes
  hub/constants.py
  hub/core/chunk_engine/tests/common.py
  hub/tests/common.py
Labels: v2

#860 [2.0] Integrate the API with the new core
  conftest.py
  hub/api/dataset.py
  hub/api/tensor.py
  hub/api/tests/__init__.py
  hub/api/tests/test_api.py
  hub/constants.py
  hub/core/chunk_engine/read.py
  hub/core/chunk_engine/tests/common.py
  hub/core/chunk_engine/tests/test_benchmarks.py
  hub/core/chunk_engine/tests/test_fixed_shapes.py
  hub/core/chunk_engine/tests/test_utils.py
  hub/core/chunk_engine/write.py
  hub/core/storage/__init__.py
  hub/core/tests/common.py
  hub/util/array.py
  hub/util/exceptions.py
  hub/util/path.py
Labels: v2

#881 Doc/2.0/contributing
  CONTRIBUTING.md
  conftest.py
  hub/tests/common.py
Labels: v2
