Repository activeloopai/deeplake, pull requests merged in 2021-06, with the labels that each got.

#897 changed read me
  README.md
Labels: cla:signed

#902 [2.0] Integer indexing and Index class
  hub/api/dataset.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/core/chunk_engine/read.py
  hub/util/index.py
  hub/util/slice.py
  hub/util/tests/test_index.py
Labels: v2

#875 [2.0] Basic Hub CLI
  hub/__init__.py
  hub/cli/__init__.py
  hub/cli/auth.py
  hub/cli/commands.py
  hub/cli/test_cli.py
  hub/client/__init__.py
  hub/client/client.py
  hub/client/config.py
  hub/client/test_client.py
  hub/client/utils.py
  hub/util/exceptions.py
  setup.py
Labels: v2

#840 Add compression
  .circleci/config.yml
  hub/core/compression/__init__.py
  hub/core/compression/base.py
  hub/core/compression/constants.py
  hub/core/compression/jpeg.py
  hub/core/compression/lz4.py
  hub/core/compression/numpy.py
  hub/core/compression/png.py
  hub/core/compression/tests/test_compression.py
  hub/core/compression/webp.py
  hub/core/compression/zstd.py
  hub/util/dataset.py
  hub/util/exceptions.py
  requirements/common.txt
Labels: v2

#908 [2.0] Implement attribute syntax for Datasets
  hub/api/dataset.py
  hub/api/tests/test_api.py
Labels: v2

#913 Adding Hub 2.0 readme
  README.md
Labels: v2

#914 [2.0] Pytorch Integration
  hub/api/dataset.py
  hub/core/storage/s3.py
  hub/integrations/__init__.py
  hub/integrations/pytorch.py
  hub/integrations/pytorch_old.py
  hub/integrations/tests/test_pytorch.py
  hub/util/check_installation.py
  hub/util/exceptions.py
  hub/util/join_chunks.py
  hub/util/remove_cache.py
  hub/util/shared_memory.py
  requirements/common.txt
Labels: v2

#904 feature/2.0/dynamic-tensors
  conftest.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/core/meta/tensor_meta.py
  hub/core/tensor.py
  hub/core/tests/common.py
  hub/core/tests/test_tensor_dynamic_shape.py
  hub/core/tests/test_tensor_failures.py
  hub/core/tests/test_tensor_fixed_shape.py
  hub/integrations/pytorch.py
  hub/integrations/tests/test_pytorch.py
  hub/util/array.py
  hub/util/exceptions.py
  hub/util/index.py
  hub/util/shape.py
  hub/util/shared_memory.py
  hub/util/tests/test_array.py
  hub/util/tests/test_shape.py
Labels: v2

#922 [2.0] Improved Indexing support
  hub/api/dataset.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/core/chunk_engine/read.py
  hub/core/index/__init__.py
  hub/core/index/index.py
  hub/core/index/tests/test_index.py
  hub/core/tensor.py
  hub/core/tests/common.py
  hub/util/array.py
  hub/util/exceptions.py
Labels: v2

#923 Add docker
  Dockerfile
Labels: v2

#942 jsonify instead of pickle
  conftest.py
  hub/constants.py
  hub/core/meta/dataset_meta.py
  hub/core/meta/index_map.py
  hub/core/meta/tensor_meta.py
  hub/core/tensor.py
  hub/core/tests/common.py
Labels: v2

#925 [2.0] Add __str__ methods for Dataset and Tensor
  hub/api/dataset.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/core/index/index.py
  hub/core/tests/test_tensor_dynamic_shape.py
  hub/core/tests/test_tensor_failures.py
  hub/util/index.py
Labels: v2

#926 [2.0] Add utility functions enabled by Index update
  hub/util/__init__.py
  hub/util/shuffle.py
  hub/util/split.py
  hub/util/tests/test_shuffle.py
  hub/util/tests/test_split.py
Labels: v2

#928 [2.0] Add version to Dataset and Tensor meta
  hub/api/dataset.py
  hub/api/tests/test_api.py
  hub/core/meta/dataset_meta.py
  hub/core/meta/tensor_meta.py
Labels: v2

#927 [2.0] Add readonly support in storage providers
  hub/api/dataset.py
  hub/constants.py
  hub/core/storage/local.py
  hub/core/storage/lru_cache.py
  hub/core/storage/memory.py
  hub/core/storage/provider.py
  hub/core/storage/s3.py
  hub/core/storage/tests/test_readonly.py
  hub/util/exceptions.py
Labels: v2

#929 [2.0] Always flush by default, add `with Dataset(...) as ds:` syntax
  hub/api/dataset.py
  hub/api/tests/test_api.py
  hub/core/meta/dataset_meta.py
  hub/core/storage/lru_cache.py
  hub/core/storage/provider.py
Labels: v2

#932 Update Dockerfile
  Dockerfile
Labels: v2

#945 Feature/2.0/tensorflow
  hub/api/dataset.py
  hub/integrations/__init__.py
  hub/integrations/tensorflow.py
  hub/integrations/tests/test_tensorflow.py
  hub/util/check_installation.py
Labels: v2

#940 Adds support for Hub cloud, ability to pass creds to dataset
  hub/api/dataset.py
  hub/api/tests/test_api.py
  hub/cli/auth.py
  hub/cli/test_cli.py
  hub/client/client.py
  hub/client/utils.py
  hub/constants.py
  hub/core/dataset.py
  hub/core/storage/__init__.py
  hub/core/storage/memory.py
  hub/core/storage/provider.py
  hub/core/storage/s3.py
  hub/core/storage/tests/test_readonly.py
  hub/util/cache_chain.py
  hub/util/exceptions.py
  hub/util/get_property.py
  hub/util/get_storage_provider.py
  hub/util/path.py
  hub/util/tag.py
  setup.py
Labels: v2

#943 Feature/2.0/meta class
  .gitignore
  hub/api/dataset.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/constants.py
  hub/core/chunk_engine/read.py
  hub/core/chunk_engine/tests/test_benchmark_chunk_engine.py
  hub/core/chunk_engine/write.py
  hub/core/meta/dataset_meta.py
  hub/core/meta/index_map.py
  hub/core/meta/index_meta.py
  hub/core/meta/meta.py
  hub/core/meta/tensor_meta.py
  hub/core/tensor.py
  hub/core/tests/common.py
  hub/core/tests/test_meta.py
  hub/core/tests/test_tensor_dynamic_shape.py
  hub/core/tests/test_tensor_failures.py
  hub/htypes.py
  hub/integrations/pytorch.py
  hub/integrations/pytorch_old.py
  hub/integrations/tensorflow.py
  hub/integrations/tests/test_pytorch.py
  hub/util/callbacks.py
  hub/util/exceptions.py
  hub/util/keys.py
Labels: v2

#930 Add tool to convert from tfds to hub dataset
  hub/integrations/tests/test_pytorch.py
  hub/integrations/tests/test_tensorflow.py
  hub/util/check_installation.py
  hub/util/from_tfds.py
  hub/util/shape.py
  hub/util/tests/test_from_tfds.py
  requirements/common.txt
  requirements/plugins.txt
  requirements/tests.txt
Labels: v2

#952 Fix/2.0/empty samples
  hub/api/tests/test_api.py
  hub/core/chunk_engine/read.py
  hub/core/chunk_engine/write.py
  hub/core/tensor.py
Labels: v2

#953 add scalar samples test (it already passes :))
  hub/api/tests/test_api.py
Labels: v2

#941 storage benchmark tests for cache read/write
  hub/core/storage/tests/test_benchmark_storage_provider.py
Labels: cla:signed, v2

#949 Fix/2.0/remove batch param
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/core/chunk_engine/flatten.py
  hub/core/chunk_engine/read.py
  hub/core/chunk_engine/tests/test_benchmark_chunk_engine.py
  hub/core/chunk_engine/write.py
  hub/core/meta/tensor_meta.py
  hub/core/tensor.py
  hub/core/tests/common.py
  hub/core/tests/test_meta.py
  hub/core/tests/test_tensor.py
  hub/core/tests/test_tensor_dynamic_shape.py
  hub/core/tests/test_tensor_failures.py
  hub/core/tests/test_tensor_fixed_shape.py
  hub/htypes.py
  hub/integrations/tests/test_pytorch.py
  hub/integrations/tests/test_tensorflow.py
  hub/util/array.py
  hub/util/tests/test_array.py
  hub/util/tests/test_from_tfds.py
  hub/util/tests/test_shuffle.py
  hub/util/tests/test_split.py
Labels: v2

#947 Fix/2.0/shape
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/integrations/tensorflow.py
  hub/util/shape.py
  hub/util/tests/test_from_tfds.py
  hub/util/tests/test_shape.py
Labels: v2

#938 Added Bugout Crash reporter to Release/2.0
  conftest.py
  hub/__init__.py
  hub/api/dataset.py
  hub/cli/auth.py
  hub/cli/commands.py
  hub/client/config.py
  hub/util/bugout_reporter.py
  requirements/common.txt
Labels: cla:signed, v2

#959 [2.0] Change Dataset.__len__ and Tensor.__len__ to account for Index
  hub/api/dataset.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/core/index/index.py
  hub/util/tests/test_split.py
Labels: v2

#960 Feature/2.0/transforms
  hub/__init__.py
  hub/api/dataset.py
  hub/constants.py
  hub/core/chunk_engine/chunker.py
  hub/core/chunk_engine/tests/test_chunker.py
  hub/core/chunk_engine/write.py
  hub/core/compute/__init__.py
  hub/core/compute/process.py
  hub/core/compute/provider.py
  hub/core/compute/thread.py
  hub/core/meta/tensor_meta.py
  hub/core/transform/test_transform.py
  hub/core/transform/transform.py
  hub/htypes.py
  hub/util/callbacks.py
  hub/util/exceptions.py
  hub/util/remove_cache.py
  hub/util/transform.py
Labels: v2

#961 Feature/2.0/compression [sample-wise]
  .circleci/config.yml
  conftest.py
  hub/__init__.py
  hub/api/dataset.py
  hub/api/load.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/api/tests/test_api_with_compression.py
  hub/constants.py
  hub/core/chunk_engine/read.py
  hub/core/chunk_engine/tests/test_benchmark_chunk_engine.py
  hub/core/chunk_engine/write.py
  hub/core/compression.py
  hub/core/compression/__init__.py
  hub/core/compression/base.py
  hub/core/compression/constants.py
  hub/core/compression/jpeg.py
  hub/core/compression/lz4.py
  hub/core/compression/numpy.py
  hub/core/compression/png.py
  hub/core/compression/tests/test_compression.py
  hub/core/compression/webp.py
  hub/core/compression/zstd.py
  hub/core/meta/index_meta.py
  hub/core/meta/tensor_meta.py
  hub/core/sample.py
  hub/core/tensor.py
  hub/core/tests/common.py
  hub/core/tests/test_compression.py
  hub/core/tests/test_meta.py
  hub/htypes.py
  hub/integrations/pytorch.py
  hub/integrations/tests/test_pytorch.py
  hub/integrations/tests/test_tensorflow.py
  hub/tests/common.py
  hub/tests/dummy_data/compressed_images/cat.jpeg
  hub/tests/dummy_data/compressed_images/flower.png
  hub/util/dataset.py
  hub/util/exceptions.py
  hub/util/tests/test_load.py
  hub/util/transform.py
  requirements/requirements.txt
Labels: v2

#955 Fix/2.0/np dtype
  hub/api/dataset.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/core/meta/tensor_meta.py
  hub/core/tests/test_tensor_failures.py
  hub/util/exceptions.py
Labels: v2

#971 set `USE_UNIFORM_COMPRESSION_PER_SAMPLE` to `True`
  hub/constants.py
Labels: v2

#965 [2.0] Add bbox, video, binary_mask, segment_mask htypes
  hub/api/tests/test_api.py
  hub/htypes.py
Labels: v2

#958 [2.0] Add scalar outputs for numpy(aslist=True)
  hub/api/tests/test_api.py
  hub/core/index/index.py
  hub/core/tensor.py
Labels: v2

#973 [2.0] Fix bug with shuffle utility function
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/core/tensor.py
  hub/util/shuffle.py
  hub/util/tests/test_shuffle.py
Labels: v2

#974 [2.0] Remove dataclass from index.py
  hub/core/index/index.py
Labels: v2

#968 Fix/2.0/scalars
  hub/api/tests/test_api.py
  hub/core/tensor.py
Labels: bug, v2

#975 [2.0] Alias __repr__ to __str__ for Dataset and Tensor
  hub/api/dataset.py
  hub/api/tensor.py
Labels: v2

#977 [2.0] Minor improvements to docstrings
  hub/api/dataset.py
  hub/api/tensor.py
  hub/util/get_storage_provider.py
Labels: v2

#981 [2.0] Bump humbug to 0.2.6
  requirements/common.txt
Labels: v2

#993 [2.0] Add necessary messages for dataset operations
  hub/api/dataset.py
  hub/client/client.py
  hub/core/storage/tests/test_storage_provider.py
Labels: cla:signed

#982 Fix/2.0/login message
  hub/cli/auth.py
  hub/cli/test_cli.py
Labels: cla:signed

#991 [2.0] Limit scope of API reference docs
  .gitignore
  CONTRIBUTING.md
  hub/__init__.py
  hub/api/dataset.py
  hub/htypes.py
  hub/util/__init__.py
  pdoc/templates/config.mako
  pdoc/templates/css.mako
Labels: v2

#992 [2.0] Add back windows CI tests
  .circleci/config.yml
Labels: v2

#997 [2.0] Suppress logs in tests
  conftest.py
Labels: v2

#989 Add htype, compression to transform
  hub/core/transform/test_transform.py
  hub/core/transform/transform.py
  hub/util/tests/test_transform.py
  hub/util/transform.py
Labels: v2
