Repository activeloopai/deeplake, pull requests merged in 2021-02, with the labels that each got.

#542 hub and huggingface transformers tutorial added.
  examples/nlp_using_hub.ipynb
Labels: documentation

#544 Add notebooks section in README.md
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#548 Evaluate multiple arguments using pytest parameterized
  hub/schema/tests/test_features.py
Labels: good first issue, help wanted

#559 Add Use Case: Creating an dataset for DL prediction of crop yield
  examples/Senegal_yields_regions.csv
  examples/Use_Case_DL_crop_yield_prediction_dataset_with_Activeloop.ipynb
Labels: documentation

#585 update example notebooks with pip
  examples/nlp_using_hub.ipynb
  examples/tutorial/Tutorial 1a - Uploading Images.ipynb
  examples/tutorial/Tutorial 1b - Uploading Dataframes.ipynb
  examples/tutorial/Tutorial 1c - Uploading Audio.ipynb
  examples/tutorial/Tutorial 2 - Retrieving Remote Data.ipynb
  examples/tutorial/Tutorial 3 - Transforming Data.ipynb
  examples/tutorial/Tutorial 4 - What are Dynamic Tensors.ipynb
Labels: dataset, documentation

#576 Refactored Dataset Class
  hub/api/dataset.py
  hub/api/integrations.py
Labels: enhancement

#592 Tutorial for working with Audio
  examples/tutorial/MiniLibriMix Tutorial.ipynb
Labels: documentation, help wanted

#605 Add MinIO to Data Storage docs
  docs/source/simple.md
Labels: documentation

#604 Replaced commit() with flush() in documentation.
  README.md
  README_CN.md
  docs/source/concepts/dataset.md
  docs/source/simple.md
  docs/source/tutorials/new_api.md
  examples/Use_Case_DL_crop_yield_prediction_dataset_with_Activeloop.ipynb
  examples/basic.py
  examples/big_image.py
  examples/large_dataset_build.py
  examples/mnist_upload_speed_benchmark.py
  examples/new_api_intro.py
  hub/api/dataset.py
Labels: documentation

#534 Put zarr, tileDB and hub benchmarks in one file
  benchmarks/benchmark_sequential_access.py
  benchmarks/benchmark_tiledb_hub.py
  benchmarks/benchmark_zarr_hub.py
Labels: enhancement

#608 add README in Turkish
  README.md
  README_TR.md
Labels: documentation

#619 change ds.commit() to ds.flush() in README.md
  README.md
Labels: documentation

#630 Improve Directory Structure of Examples
  README.md
  examples/notebooks/Use_Case_DL_crop_yield_prediction_dataset_with_Activeloop.ipynb
  examples/notebooks/nlp_using_hub.ipynb
  examples/notebooks/to_pytorch_example.ipynb
  examples/old/load.py
  examples/old/upload_tfds.py
Labels: documentation, enhancement

#616 Removed Assertions from shape_detector.py and added exceptions
  examples/large_dataset_build.py
  hub/store/shape_detector.py
  hub/store/tests/test_shape_detector.py
Labels: bug
