Repository activeloopai/deeplake, pull requests merged in 2021-07, with the labels that each got.

#1000 Multiple fixes to transform
  hub/core/chunk_engine/write.py
  hub/core/transform/test_transform.py
  hub/core/transform/transform.py
  hub/util/exceptions.py
  hub/util/transform.py
Labels: v2

#1006 [2.0] Better negative indexing
  hub/api/tests/test_api.py
  hub/core/index/index.py
  hub/core/index/tests/test_index.py
  hub/tests/common.py
Labels: v2

#1011 Removed transform code temporarily after refactor
  hub/__init__.py
  hub/core/transform/__init__.py
  hub/core/transform/test_transform.py
  hub/core/transform/transform.py
  hub/util/tests/test_transform.py
  hub/util/transform.py
Labels: v2

#1007 Update Pytorch after refactor
  hub/api/dataset.py
  hub/core/chunk_engine.py
  hub/integrations/pytorch.py
  hub/integrations/pytorch_old.py
  hub/integrations/tests/test_pytorch.py
Labels: v2

#1015 quick fix on leak
  hub/core/chunk.py
  hub/core/chunk_engine.py
  hub/core/meta/encode/shape.py
  hub/core/meta/encode/tests/test_shape_encoder.py
Labels: v2

#1005 [mega-PR] NEW CHUNK ENGINE!!!
  conftest.py
  hub/__init__.py
  hub/api/dataset.py
  hub/api/load.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/api/tests/test_api_with_compression.py
  hub/constants.py
  hub/core/chunk.py
  hub/core/chunk_engine.py
  hub/core/chunk_engine/flatten.py
  hub/core/chunk_engine/read.py
  hub/core/chunk_engine/tests/test_benchmark_chunk_engine.py
  hub/core/chunk_engine/tests/test_full_benchmark_chunk_engine.py
  hub/core/chunk_engine/write.py
  hub/core/compression.py
  hub/core/dataset.py
  hub/core/meta/dataset_meta.py
  hub/core/meta/encode/__init__.py
  hub/core/meta/encode/byte_positions.py
  hub/core/meta/encode/chunk_id.py
  hub/core/meta/encode/shape.py
  hub/core/meta/encode/tests/__init__.py
  hub/core/meta/encode/tests/test_byte_positions_encoder.py
  hub/core/meta/encode/tests/test_chunk_id_encoder.py
  hub/core/meta/encode/tests/test_shape_encoder.py
  hub/core/meta/index_meta.py
  hub/core/meta/meta.py
  hub/core/meta/tensor_meta.py
  hub/core/sample.py
  hub/core/storage/cachable.py
  hub/core/storage/lru_cache.py
  hub/core/storage/provider.py
  hub/core/tensor.py
  hub/core/tests/common.py
  hub/core/tests/test_compression.py
  hub/core/tests/test_meta.py
  hub/core/tests/test_tensor.py
  hub/core/tests/test_tensor_failures.py
  hub/core/transform/__init__.py
  hub/core/transform/test_transform.py
  hub/core/transform/transform.py
  hub/htypes.py
  hub/integrations/pytorch.py
  hub/integrations/pytorch_old.py
  hub/integrations/tests/test_pytorch.py
  hub/integrations/tests/test_tensorflow.py
  hub/tests/common.py
  hub/util/cache_chain.py
  hub/util/callbacks.py
  hub/util/exceptions.py
  hub/util/keys.py
  hub/util/path.py
  hub/util/tests/test_from_tfds.py
  hub/util/tests/test_transform.py
  hub/util/transform.py
Labels: v2

#1024 [small] Fix/2.0/readonly
  hub/api/dataset.py
  hub/api/tests/test_readonly.py
  hub/core/chunk_engine.py
  hub/core/storage/lru_cache.py
Labels: bug, v2

#1035 Refactor/fstrings
  .circleci/config.yml
  conftest.py
  hub/client/client.py
  hub/client/config.py
  hub/core/meta/tensor_meta.py
  hub/tests/common.py
  hub/util/exceptions.py
  hub/util/shape.py
  hub/util/subscript_namedtuple.py
  setup.py
Labels: cla:signed

#1023 [small] Update/2.0/hub cloud test
  hub/api/tests/test_api.py
Labels: v2

#1026 [small] pytorch readonly error bug fix
  hub/integrations/pytorch.py
  hub/integrations/pytorch_old.py
  hub/integrations/tests/test_pytorch.py
  hub/util/dataset.py
Labels: bug, v2

#1052 Changed from master to main
  .github/workflows/release-drafter.yml
Labels: cla:signed

#1058 Fixes an issue in which reporting configuration file was not being created if its parent directory didn't exist.
  hub/__init__.py
  hub/util/bugout_reporter.py
Labels: cla:signed

#1064 [Small PR] Renames hub.load to hub.read
  hub/__init__.py
  hub/api/read.py
  hub/api/tensor.py
  hub/api/tests/test_api_with_compression.py
  hub/util/tests/test_read.py
Labels: v2

#1063 Added "dataset" class for interacting with underlying "Dataset" class
  hub/__init__.py
  hub/api/dataset.py
  hub/api/tensor.py
  hub/api/tests/test_api.py
  hub/api/tests/test_api_with_compression.py
  hub/api/tests/test_dataset.py
  hub/api/tests/test_readonly.py
  hub/constants.py
  hub/core/dataset.py
  hub/core/storage/s3.py
  hub/core/tensor.py
  hub/integrations/pytorch/pytorch_old.py
  hub/integrations/tests/test_pytorch.py
  hub/integrations/tests/test_tensorflow.py
  hub/tests/dataset_fixtures.py
  hub/tests/path_fixtures.py
  hub/tests/storage_fixtures.py
  hub/util/exceptions.py
  hub/util/from_tfds.py
  hub/util/keys.py
  hub/util/path.py
  hub/util/storage.py
Labels: v2

#1078 [small] Remove dataset link during creation of Hub datasets
  hub/client/client.py
Labels: cla:signed

#1079 BUGGER_OFF=true when running tests in Circle CI.
  .circleci/config.yml
Labels: cla:signed
