Repository activeloopai/deeplake, pull requests merged in 2021-04, with the labels that each got.

#675 Feature/examples
  examples/README.md
  examples/generate_ds_transform.py
  examples/train_pytorch.py
  examples/train_tensorflow.py
  examples/transform_dataset.py
Labels: documentation

#755 Provide link to app when dataset is created
  hub/client/hub_control.py
Labels: enhancement

#733 Added WebDataset Hub benchmarks
  benchmarks/webdataset_hub_benchmarks.ipynb
Labels: documentation

#743 Working with Images documentation
  docs/source/img/image_link.rst
  docs/source/img/working_with_images1.png
  docs/source/img/working_with_images2.png
  docs/source/index.rst
  docs/source/working_with_images.md
Labels: documentation

#744 Fixes/class label shape
  hub/api/dataset.py
  hub/api/dataset_utils.py
  hub/api/datasetview.py
  hub/api/tensorview.py
  hub/api/tests/test_dataset.py
  hub/exceptions.py
Labels: bug
