Repository activeloopai/deeplake, pull requests merged in 2021-03, with the labels that each got.

#629 add notebook example for creating dataset for object detection and instance segmentation
  examples/tutorial/Hub Tutorial - VHR-10 COCO Dataset.ipynb
Labels: documentation, help wanted

#628 Hub version command cli
  hub/cli/auth.py
  hub/cli/command.py
  hub/version.py
Labels: enhancement, help wanted

#640 Add README in French
  README_FR.md
Labels: documentation

#624 Hub crash and system information reports using Bugout
  hub/__init__.py
  hub/cli/auth.py
  hub/cli/command.py
  hub/config.py
  hub/exceptions.py
  hub/report.py
  hub/version.py
  requirements.txt
  setup.py
Labels: enhancement, feature-discussion

#655 Turned reporting off when tests are run
  conftest.py
  hub/report.py
Labels: enhancement

#610 Release/v1.3.0 [Version Control]
  README_translations/README_TR.md
  benchmarks/benchmark_sequential_write.py
  docs/source/concepts/versioning.md
  docs/source/index.rst
  examples/new_api_intro.py
  examples/versioning_eg_1.py
  examples/versioning_eg_3.py
  hub/api/dataset.py
  hub/api/dataset_utils.py
  hub/api/datasetview.py
  hub/api/tensorview.py
  hub/api/tests/test_converters.py
  hub/api/tests/test_dataset.py
  hub/api/tests/test_version_control.py
  hub/api/versioning.py
  hub/compute/ray.py
  hub/compute/tests/test_ray.py
  hub/compute/transform.py
  hub/defaults.py
  hub/exceptions.py
  hub/store/metastore.py
  hub/store/store.py
  hub/store/tests/test_meta_storage.py
  setup.py
Labels: enhancement

#666 include consent language in readme
  README.md
Labels: documentation

#672 Add Tutorial for Working with Text on Hub
  docs/source/index.rst
  docs/source/working_with_text.md
  examples/notebooks/Getting_Started_with_Text_on_Hub.ipynb
  hub/compute/transform.py
  hub/version.py
Labels: documentation

#673 Bumped humbug dependency version to ">=0.1.6"
  requirements.txt
Labels: enhancement

#654 Update schema docs
  docs/source/api.md
  hub/schema/audio.py
  hub/schema/bbox.py
  hub/schema/class_label.py
  hub/schema/image.py
  hub/schema/text.py
Labels: documentation

#668 Add unit test for utils.py
  hub/tests/test_utils.py
Labels: documentation

#683 Removed version information in setup.py
  setup.py
Labels: documentation

#705 update tensors from generic types to hub schema representations
  examples/notebooks/Hello_Objectron.ipynb
Labels: dataset, enhancement

#711 Feature: CSV parsing for hub.auto
  docs/source/concepts/dataset.md
  hub/auto/__init__.py
  hub/auto/infer.py
  hub/auto/tabular/__init__.py
  hub/auto/tabular/csv.py
  hub/auto/tests/dummy_data/tabular/multiple_csv/MOCK_DATA(1).csv
  hub/auto/tests/dummy_data/tabular/multiple_csv/MOCK_DATA(2).csv
  hub/auto/tests/dummy_data/tabular/multiple_csv/MOCK_DATA(3).csv
  hub/auto/tests/dummy_data/tabular/multiple_csv/MOCK_DATA(4).csv
  hub/auto/tests/dummy_data/tabular/multiple_csv/MOCK_DATA.csv
  hub/auto/tests/dummy_data/tabular/single_csv/MOCK_DATA.csv
  hub/auto/tests/test_tabular_data.py
  hub/auto/util.py
  hub/utils.py
  requirements-optional.txt
  requirements.txt
Labels: enhancement
